version: "3.9"
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: presidency_backend
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8080:8080"

volumes:
  mysql_data:
